{{- range $name, $config := .Values.services }}
{{- if and $config.ingress $config.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $config.containerName }}-ingress 
  namespace: {{ $.Values.namespace }}
  labels:
    name: {{ $config.containerName }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $config.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $config.containerName }}
            port:
              number: {{ $config.port }}
{{- end }}
{{- end }}